---
- name: Install dynatrace
  hosts: all
  become: true
  roles:
    - role: dynatrace.oneagent
  vars:
    dynatrace_environment_url: mbb49765.live.dynatrace.com
    dynatrace_paas_token: dt0c01.PRCFV7CYZTJZA2AYK5PXEJ6E.UAG34VC3RGXG5OR3NERPN7A5QFRLHF72TNTRWYTQ5HWB4RDZEXRUAC6QLYXLVYV2
    dynatrace_oneagent_install_args:
      INFRA_ONLY: 0
      HOST_GROUP: "{{ host_group }}"
    dynatrace_oneagent_host_tags: ""
    dynatrace_oneagent_host_metadata: batch={{ patch_batch }} friendly_name={{ friendly_name }} team=sams3pi